[[redirects]]
  from = "/"
  to = "/admin.html"
  status = 200
  conditions = {Host = ["admin.lava-rapido-vt.com.br"]}

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200
  conditions = {Host = ["login.lava-rapido-vt.com.br"]}
